'use strict';
const $=id=>document.getElementById(id),val=id=>Number($(id).value),fmt=x=>x===null?'—':Number(x).toFixed(6);
function inputs(){return [val('spot'),val('strike'),val('days')/365,val('rate')/100,val('vol')/100,$('dividend-mode').value==='cash'?0:val('yield')/100]}
function treeOptions(){const raw=$('cash-dividends').value.trim();const dividends=$('dividend-mode').value==='cash'&&raw?raw.split(/\n/).map((line,i)=>{const fields=line.split(',').map(x=>x.trim());if(fields.length!==2||fields.some(x=>x===''))throw Error('Dividend line '+(i+1)+': enter days, amount.');const [days,amount]=fields.map(Number);if(!Number.isFinite(days)||!Number.isFinite(amount)||days<=0||amount<0)throw Error('Dividend days must be positive and amounts nonnegative.');return {timeYears:days/365,amount}}):[];return {steps:val('tree-steps'),exercise:$('exercise').value,dividends}}
function pricing(){try{const a=inputs(),opts=treeOptions(),tree=opts.exercise==='american'||opts.dividends.length>0,o=tree?AmericanMath.option(...a,opts):OptionMath.option(...a);$('price-results').innerHTML=[['Option value',o.call,o.put],['Delta',o.deltaCall,o.deltaPut],['Gamma',o.gammaCall===undefined?o.gamma:o.gammaCall,o.gammaPut===undefined?o.gamma:o.gammaPut],['Alpha (Gamma / daily Theta)',o.alphaCall,o.alphaPut],['Vega / 1% vol',o.vegaCall===undefined?o.vega:o.vegaCall,o.vegaPut===undefined?o.vega:o.vegaPut],['Theta / day',o.thetaCall,o.thetaPut],['Rho / 1% rate',o.rhoCall,o.rhoPut]].map(r=>`<tr><th>${r[0]}</th><td>${fmt(r[1])}</td><td>${fmt(r[2])}</td></tr>`).join('');const pvDiv=opts.dividends.filter(d=>d.timeYears<a[2]).reduce((sum,d)=>sum+d.amount*Math.exp(-a[3]*d.timeYears),0),rhs=(a[0]-pvDiv)*Math.exp(-a[5]*a[2])-a[1]*Math.exp(-a[3]*a[2]),eo=OptionMath.option(a[0]-pvDiv,...a.slice(1));$('parity-result').textContent=fmt(rhs);$('parity-detail').textContent=`European reference call − put: ${fmt(eo.call-eo.put)}. Parity difference: ${fmt(eo.call-eo.put-rhs)}. ${opts.exercise==='american'?'American values are not subject to this European equality.':''}`;$('price-model').textContent=tree?`${opts.exercise==='american'?'American':'European'} CRR lattice · ${opts.steps} steps${opts.dividends.length?' · escrowed cash-dividend approximation':''}. Changing steps can change prices and numerical Greeks.`:'European Black-Scholes-Merton · continuous dividend yield.';$('price-error').textContent='';}catch(e){$('price-error').textContent=e.message;$('price-results').innerHTML='';$('parity-result').textContent='—';$('parity-detail').textContent='Enter valid pricing inputs.'}}
$('dividend-mode').addEventListener('change',()=>{const cash=$('dividend-mode').value==='cash';$('cash-dividends-field').hidden=!cash;$('yield').disabled=cash});
$('price-form').addEventListener('submit',ev=>{ev.preventDefault();pricing()});$('solve-iv').addEventListener('click',()=>{try{let [S,K,T,r,,q]=inputs();const opts=treeOptions(),tree=opts.exercise==='american'||opts.dividends.length>0,v=tree?AmericanMath.implied($('iv-type').value,val('iv-price'),S,K,T,r,q,opts):OptionMath.implied($('iv-type').value,val('iv-price'),S,K,T,r,q);$('iv-result').textContent=`Implied volatility: ${(v*100).toFixed(6)}% per year (${tree?'selected CRR model':'European BSM'}).`;}catch(e){$('iv-result').textContent=e.message}});
function payoff(){try{let strategy=$('strategy').value,p={spot:val('p-spot'),strike:val('p-strike'),upper:val('p-upper'),callPremium:val('p-call'),putPremium:val('p-put'),multiplier:val('p-multiplier'),contracts:val('p-contracts')};if(!Object.values(p).every(Number.isFinite)||p.spot<0||p.strike<=0||p.callPremium<0||p.putPremium<0||p.multiplier<=0||p.contracts<1||!Number.isInteger(p.contracts)||val('p-expiry')<0||strategy==='shortStrangle'&&p.upper<=p.strike)throw Error('Use valid nonnegative prices and premiums, positive strike/multiplier, whole contracts, and an upper strike above the lower strike.');$('p-result').textContent=OptionMath.payoff(strategy,val('p-expiry'),p).toFixed(2);const xmax=Math.max(p.spot,p.strike,p.upper,val('p-expiry'),1)*1.6,pts=Array.from({length:161},(_,i)=>[i*xmax/160,OptionMath.payoff(strategy,i*xmax/160,p)]);let ymin=Math.min(0,...pts.map(p=>p[1])),ymax=Math.max(0,...pts.map(p=>p[1]));if(ymax===ymin)ymax=ymin+1;let pad=(ymax-ymin)*.1;ymin-=pad;ymax+=pad;let x=x=>55+560*x/xmax,y=y=>255-220*(y-ymin)/(ymax-ymin);$('payoff-chart').innerHTML=`<line x1="55" y1="${y(0)}" x2="615" y2="${y(0)}" stroke="#aebeb3"/><line x1="55" y1="35" x2="55" y2="255" stroke="#aebeb3"/><path d="${pts.map((p,i)=>(i?'L':'M')+x(p[0]).toFixed(2)+' '+y(p[1]).toFixed(2)).join(' ')}" fill="none" stroke="#234b3c" stroke-width="3"/><text x="55" y="281">0</text><text x="540" y="281">${xmax.toFixed(1)}</text><text x="245" y="296">Underlying price at expiry</text><text x="10" y="30">P&amp;L</text><text x="60" y="45">${ymax.toFixed(0)}</text><text x="60" y="250">${ymin.toFixed(0)}</text>`;$('p-risk').textContent=['coveredPut','shortStraddle','shortStrangle'].includes(strategy)?'This strategy has unlimited loss potential as the underlying price rises.':'Inspect the course reading for the strategy’s maximum profit, loss and breakeven.';$('payoff-error').textContent='';}catch(e){$('payoff-error').textContent=e.message;$('p-result').textContent='—';$('payoff-chart').innerHTML=''}}
$('payoff-form').addEventListener('submit',ev=>{ev.preventDefault();payoff()});
function futures(){try{if(!Number.isInteger(val('f-contracts')))throw Error('Contracts must be a whole number.');let o=OptionMath.futures(val('f-entry'),val('f-exit'),val('f-multiplier'),val('f-contracts'),val('f-side'),val('f-initial'),val('f-maintenance'));$('f-results').innerHTML=[['Profit / loss',o.pnl.toFixed(2)],['Margin balance after P&L',o.equity.toFixed(2)],['Below maintenance?',o.marginCall?'Yes':'No'],['Illustrative top-up',o.topUp.toFixed(2)]].map(r=>`<tr><th>${r[0]}</th><td>${r[1]}</td></tr>`).join('');$('futures-error').textContent='';}catch(e){$('futures-error').textContent=e.message;$('f-results').innerHTML=''}}
$('futures-form').addEventListener('submit',ev=>{ev.preventDefault();futures()});
const tabs=[...document.querySelectorAll('[data-panel]')];
function selectPanel(id){const selected=tabs.find(b=>b.dataset.panel===id)||tabs[0];tabs.forEach(b=>{const on=b===selected;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1});document.querySelectorAll('[role=tabpanel]').forEach(p=>p.hidden=p.id!==selected.dataset.panel);pricing();payoff();futures()}
tabs.forEach((btn,i)=>{btn.addEventListener('click',()=>{location.hash=btn.dataset.panel;selectPanel(btn.dataset.panel)});btn.addEventListener('keydown',ev=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(ev.key)){ev.preventDefault();const j=ev.key==='Home'?0:ev.key==='End'?tabs.length-1:(i+(ev.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[j].click();tabs[j].focus()}})});
window.addEventListener('hashchange',()=>selectPanel(location.hash.slice(1)));selectPanel(location.hash.slice(1));
