'use strict';
const STORE='derivatives-offline-v1';
function readState(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
let state=readState();
function saveState(){try{localStorage.setItem(STORE,JSON.stringify(state));return true}catch{return false}}
function updateProgress(){document.querySelectorAll('[data-item]').forEach(row=>{let status=row.querySelector('.done');if(status)status.textContent=state['done:'+row.dataset.item]?'✓':''});let counter=document.getElementById('progress');if(counter)counter.textContent=Object.keys(state).filter(k=>k.startsWith('done:')&&state[k]).length;let btn=document.getElementById('complete');if(btn)btn.textContent=state['done:'+document.body.dataset.id]?'Mark unfinished':'Mark studied';}
document.getElementById('complete')?.addEventListener('click',()=>{let key='done:'+document.body.dataset.id;state[key]=!state[key];saveState();updateProgress()});
document.querySelectorAll('.question input').forEach(input=>{let key='answer:'+document.body.dataset.id+':'+input.name;input.checked=state[key]===input.value;input.addEventListener('change',()=>{state[key]=input.value;let ok=saveState();document.getElementById('answer-status').textContent=ok?'Saved on this device.':'Storage unavailable. Use Export answers to keep your selections.'})});
document.getElementById('reset-answers')?.addEventListener('click',()=>{document.querySelectorAll('.question input').forEach(i=>{delete state['answer:'+document.body.dataset.id+':'+i.name];i.checked=false});saveState();document.getElementById('answer-status').textContent='Selections cleared.'});
document.getElementById('export')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='offline-study-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
document.getElementById('import')?.addEventListener('change',async ev=>{try{let incoming=JSON.parse(await ev.target.files[0].text());if(!incoming||Array.isArray(incoming)||typeof incoming!=='object')throw Error();for(const [k,v] of Object.entries(incoming)){if(k.startsWith('done:')&&typeof v==='boolean'||k.startsWith('answer:')&&typeof v==='string')state[k]=v;}saveState();location.reload()}catch{alert('Choose a valid progress JSON exported by this course.')}});
let filter='all';
function applyFilter(){let query=(document.getElementById('search')?.value||'').toLowerCase();document.querySelectorAll('.item').forEach(row=>row.hidden=!(filter==='all'||row.dataset.kind===filter)||!row.textContent.toLowerCase().includes(query));document.querySelectorAll('.module').forEach(s=>s.hidden=!Array.from(s.querySelectorAll('.item')).some(r=>!r.hidden));}
document.getElementById('search')?.addEventListener('input',applyFilter);document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{filter=btn.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===btn));applyFilter()}));
const video=document.querySelector('video');let captionOn=true;
if(video&&typeof SUBTITLE_CUES!=='undefined'){video.addEventListener('timeupdate',()=>{let cue=captionOn?SUBTITLE_CUES.find(c=>video.currentTime>=c.start&&video.currentTime<c.end):null;document.getElementById('caption-text').textContent=cue?.text||'';document.getElementById('captions').hidden=!cue});document.getElementById('toggle-captions').addEventListener('click',ev=>{captionOn=!captionOn;ev.target.setAttribute('aria-pressed',String(captionOn));document.getElementById('captions').hidden=!captionOn})}
updateProgress();
